// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mD1aunLqCXU7SXpMa0Q9c9KYf0oYlEE',
    appId: '1:364699996968:web:cc231d884514bbe8bb361d',
    messagingSenderId: '364699996968',
    projectId: 'cseedge-6578a',
    authDomain: 'cseedge-6578a.firebaseapp.com',
    storageBucket: 'cseedge-6578a.firebasestorage.app',
    measurementId: 'G-GY8SGTEE8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzkfhQ6N6UFogi0g7q_Qe8RwZgvKdYuzE',
    appId: '1:364699996968:android:92e558522fdb747cbb361d',
    messagingSenderId: '364699996968',
    projectId: 'cseedge-6578a',
    storageBucket: 'cseedge-6578a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIGNhKOcz4sGOMy6585_kPGSqZNwDTgg',
    appId: '1:364699996968:ios:11da9e6a28c47dfdbb361d',
    messagingSenderId: '364699996968',
    projectId: 'cseedge-6578a',
    storageBucket: 'cseedge-6578a.firebasestorage.app',
    iosClientId: '364699996968-kkam3g9i471455bkah3man1hh53ahvpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cseEdge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIGNhKOcz4sGOMy6585_kPGSqZNwDTgg',
    appId: '1:364699996968:ios:11da9e6a28c47dfdbb361d',
    messagingSenderId: '364699996968',
    projectId: 'cseedge-6578a',
    storageBucket: 'cseedge-6578a.firebasestorage.app',
    iosClientId: '364699996968-kkam3g9i471455bkah3man1hh53ahvpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cseEdge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8mD1aunLqCXU7SXpMa0Q9c9KYf0oYlEE',
    appId: '1:364699996968:web:6d4ada4a0754c641bb361d',
    messagingSenderId: '364699996968',
    projectId: 'cseedge-6578a',
    authDomain: 'cseedge-6578a.firebaseapp.com',
    storageBucket: 'cseedge-6578a.firebasestorage.app',
    measurementId: 'G-G92KRK0G8H',
  );
}
